version: "3.8"
services:
  web:
    container_name: backend_server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 3000:3000
    networks:
      - gateway

  krakend:
    container_name: krakend
    image: devopsfaith/krakend:watch
    volumes:
      - "./:/etc/krakend/"
    ports:
      - 8080:8080
    environment:
      - FC_ENABLE=1
      - FC_OUT=krakend/out.json
      - FC_PARTIALS=krakend/partials
      - FC_SETTINGS=krakend/settings/test
      - FC_TEMPLATES=krakend/templates
    networks:
      - gateway
    command: ["run", "-dc", "krakend/krakend.tmpl"]

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak

    ports:
      - 8787:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysqldb:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    networks:
      - gateway
    depends_on:
      - db
    command:
      - start-dev

  db:
    container_name: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks:
      - gateway

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
